# Build da imagem do ap-front no projeto brikz-ap. Use ./deploy.sh (build + deploy).
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - southamerica-east1-docker.pkg.dev/$PROJECT_ID/front/ap-front:$_TAG
      - --build-arg=VITE_CONTRATOS_API_BASE_URL=$_CONTRATOS_URL
      - --build-arg=VITE_FINANCIADOR_ID=$_FINANCIADOR_ID
      - --build-arg=VITE_OPTIN_API_BASE_URL=$_OPTIN_URL
      - --build-arg=VITE_AGENDA_API_BASE_URL=$_AGENDA_URL
      - --build-arg=VITE_KEYCLOAK_ISSUER=$_KEYCLOAK_ISSUER
      - --build-arg=VITE_KEYCLOAK_CLIENT_ID=$_KEYCLOAK_CLIENT_ID
      - .
images:
  - southamerica-east1-docker.pkg.dev/$PROJECT_ID/front/ap-front:$_TAG
serviceAccount: projects/brikz-ap/serviceAccounts/front-build@brikz-ap.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
